import Navbar from "../components/Layouts/Navbar";
import Sidebar from "../components/Layouts/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <div>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
