import Navbar from "../components/Layouts/Navbar";
import Sidebar from "../components/Layouts/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const bodyStyle = {
    backgroundImage: "url('/images/Background.png')",
    height: "300px",
    width: "100%",
  };

  return (
    <html lang="en">
      <body>
          <div style={bodyStyle} className="flex">
            <Sidebar />
            <div className=" flex flex-col flex-grow">
            <Navbar />
             <main className="flex-grow">{children}</main> 
            </div>
        </div>
      </body>
    </html>
  );
}
