import { Fragment } from 'react';
import Head from 'next/head';
import Navbar from '../components/Layouts/Navbar';
import Sidebar from '../components/Layouts/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const bodyStyle = {
    backgroundImage: "url('/images/Background.png')",
    height: '300px',
    width: '100%',
  };

  return (

    <Fragment>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <html lang="en">
        <body>
          <div style={bodyStyle} className="flex">
            <Sidebar />
            <div className="flex flex-col flex-grow">
              <Navbar />
              <main className="">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </Fragment>
  );
}
